[features]
seeds = false
[programs.localnet]
gifportal = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/daniel/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
