[features]
seeds = false
[programs.devnet]
gifportal = "BbM7MAyjo1gtXgtDBCjc6W4QD1ef54ratuqshNN9g6kr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/daniel/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
